on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install modules
        run: npm install
      - name: Test logs
        run: echo This is from the release
      - name: Test logs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
