on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Test logs
        run: echo This is from the release
      - name: Test logs
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
